"""add_chat_system

Revision ID: 0b7c50d205a3
Revises: 22708302b1c8
Create Date: 2025-06-23 06:22:54.987415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b7c50d205a3'
down_revision = '22708302b1c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_user_id_users', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.drop_column('user_profiles', 'updated_at')
    op.drop_constraint('user_stats_user_id_fkey', 'user_stats', type_='foreignkey')
    op.create_foreign_key(None, 'user_stats', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stats', type_='foreignkey')
    op.create_foreign_key('user_stats_user_id_fkey', 'user_stats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_profiles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('fk_transactions_user_id_users', 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ### 