"""add onboarding fields to user profile

Revision ID: 22708302b1c8
Revises: f43271a41b9d
Create Date: 2024-06-20 15:40:08.513518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22708302b1c8'
down_revision = 'f43271a41b9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('gender', sa.String(length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('income_source', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('income_stability', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('monthly_expenses', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('spending_categories', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('goals', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('financial_confidence', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('spending_impulsiveness', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('financial_stress', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('saving_frequency', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('tracks_expenses', sa.Boolean(), nullable=True))
    op.add_column('user_profiles', sa.Column('used_financial_apps', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('wants_motivation', sa.Boolean(), nullable=True))
    
    op.alter_column('user_profiles', 'monthly_income',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('user_profiles', 'weekly_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_profiles', 'weeks_per_month',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_profiles', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'wants_motivation')
    op.drop_column('user_profiles', 'used_financial_apps')
    op.drop_column('user_profiles', 'tracks_expenses')
    op.drop_column('user_profiles', 'saving_frequency')
    op.drop_column('user_profiles', 'financial_stress')
    op.drop_column('user_profiles', 'spending_impulsiveness')
    op.drop_column('user_profiles', 'financial_confidence')
    op.drop_column('user_profiles', 'goals')
    op.drop_column('user_profiles', 'spending_categories')
    op.drop_column('user_profiles', 'monthly_expenses')
    op.drop_column('user_profiles', 'income_stability')
    op.drop_column('user_profiles', 'income_source')
    op.drop_column('user_profiles', 'gender')
    op.drop_column('user_profiles', 'age')
    op.drop_column('user_profiles', 'name')
    
    op.alter_column('user_profiles', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('user_profiles', 'weeks_per_month',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_profiles', 'weekly_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_profiles', 'monthly_income',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               nullable=False)
    # ### end Alembic commands ### 