"""add account model

Revision ID: bac9f5f4337d
Revises: 1022e9da5210
Create Date: 2025-06-23 08:20:30.557777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac9f5f4337d'
down_revision = '1022e9da5210'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 